name: "Protoc action"
description: "Action for generate from client and server from protofiles"
author: "PxyUp"
inputs:
  path:
    description: "Path and arguments for protoc"
    required: true
  parent:
    description: "Parent Directory for relative protc generation"
    default: proto
    required: false
outputs:
  success: # id of output
    description: "Success"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}
    - ${{ inputs.parent }}
branding:
  icon: "aperture"
  color: "green"
